services:

  mongodb:
    image: mongo:8.2.6
    container_name: nossasaude-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:4.0
    container_name: nossasaude-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=sa-east-1
      - AWS_DEFAULT_REGION=sa-east-1
      - LOCALSTACK_HOST=localhost
    volumes:
      - localstack_data:/var/lib/localstack
      - ./scripts/localstack-init.sh:/etc/localstack/init/ready.d/init.sh:ro
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mongodb_data:
  localstack_data:
